xgb:
  params:
    max_depth: 3
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 1.0
    min_child_weight: 3
    gamma: 0.5
  method: standardize
  n_features: 45
  features:
  - SpMax_B(m)
  - nN
  - SpMax_L
  - SpPosA_B(p)
  - J_Dz(e)
  - MolLogP
  - SM6_B(m)
  - SpMax_A
  - Psi_i_A
  - SdssC
  - homo_lumo_gap
  - F02(C-N)
  - TPSA
  - TI2_L
  - nCp
  - HyWi_B(m)
  - nO
  - LOC
  - nHM
  - Me
  - MolWt
  - C%
  - SM6_L
  - SdO
  - Psi_i_1d
  - Mi
  - nX
  - NssssC
  - nArCOOR
  - nCb-
  - F03(C-O)
  - nHDon
  - C-026
  - F03(C-N)
  - nCrt
  - F04(C-N)
  - B03(C-Cl)
  - nArNO2
  - nCIR
  - nN-N
  - N-073
  - nCRX3
  - F01(N-N)
  - B04(C-Br)
  - B01(C-Br)
  provenance:
    tuned: '2026-08-25'
    cv_f1: 0.809
    test_f1: 0.8
logreg:
  params:
    C: 0.1
    l1_ratio: 0.0
  method: standardize
  n_features: 30
  features:
  - nCb-
  - nHM
  - nN
  - nO
  - nArNO2
  - nN-N
  - F02(C-N)
  - NssssC
  - HyWi_B(m)
  - nCrt
  - Psi_i_A
  - C%
  - B03(C-Cl)
  - LOC
  - SpPosA_B(p)
  - SpMax_L
  - nX
  - SdO
  - nArCOOR
  - J_Dz(e)
  - SM6_B(m)
  - F03(C-O)
  - MolWt
  - TPSA
  - F04(C-N)
  - SdssC
  - C-026
  - N-073
  - nCp
  - homo_lumo_gap
  provenance:
    tuned: '2026-08-25'
    cv_f1: 0.794
    test_f1: 0.797
gcn:
  params:
    hidden_dim: 64
    n_gcn_layers: 2
    dropout: 0.2
    lr: 0.001
    weight_decay: 0.0001
    batch_size: 32
  method: standardize
  n_features: 45
  features:
  - SpMax_B(m)
  - nN
  - SpMax_L
  - SpPosA_B(p)
  - J_Dz(e)
  - MolLogP
  - SM6_B(m)
  - SpMax_A
  - Psi_i_A
  - SdssC
  - homo_lumo_gap
  - F02(C-N)
  - TPSA
  - TI2_L
  - nCp
  - HyWi_B(m)
  - nO
  - LOC
  - nHM
  - Me
  - MolWt
  - C%
  - SM6_L
  - SdO
  - Psi_i_1d
  - Mi
  - nX
  - NssssC
  - nArCOOR
  - nCb-
  - F03(C-O)
  - nHDon
  - C-026
  - F03(C-N)
  - nCrt
  - F04(C-N)
  - B03(C-Cl)
  - nArNO2
  - nCIR
  - nN-N
  - N-073
  - nCRX3
  - F01(N-N)
  - B04(C-Br)
  - B01(C-Br)
  provenance:
    tuned: '2026-08-25'
    cv_f1: 0.804
    test_f1: 0.795
