xgb:
  params:
    max_depth: 6
    learning_rate: 0.2
    subsample: 0.6
    colsample_bytree: 0.8
    min_child_weight: 1
    gamma: 1.0
  method: standardize
  n_features: 20
  features:
  - SpMax_B(m)
  - SpPosA_B(p)
  - SpMax_L
  - wbo_max
  - J_Dz(e)
  - MolLogP
  - ip
  - fukui_plus_max
  - Psi_i_1d
  - nN
  - SpMax_A
  - F02(C-N)
  - SM6_L
  - homo_lumo_gap
  - LOC
  - SM6_B(m)
  - TPSA
  - fukui_minus_max
  - TI2_L
  - SdssC
  provenance:
    tuned: '2026-08-25'
    cv_f1: 0.805
    test_f1: 0.764
logreg:
  params:
    C: 3
    l1_ratio: 1.0
  method: normalize
  n_features: 20
  features:
  - NssssC
  - nCb-
  - nHM
  - nArNO2
  - nCrt
  - nO
  - nN-N
  - F02(C-N)
  - ip
  - SM6_B(m)
  - nN
  - C%
  - LOC
  - nArCOOR
  - F03(C-O)
  - J_Dz(e)
  - SdssC
  - Psi_i_A
  - nHDon
  - HyWi_B(m)
  provenance:
    tuned: '2026-08-25'
    cv_f1: 0.789
    test_f1: 0.787
gcn:
  params:
    hidden_dim: 64
    n_gcn_layers: 3
    dropout: 0.1
    lr: 0.001
    weight_decay: 0.0
    batch_size: 64
  method: standardize
  n_features: 20
  features:
  - SpMax_B(m)
  - SpPosA_B(p)
  - SpMax_L
  - wbo_max
  - J_Dz(e)
  - MolLogP
  - ip
  - fukui_plus_max
  - Psi_i_1d
  - nN
  - SpMax_A
  - F02(C-N)
  - SM6_L
  - homo_lumo_gap
  - LOC
  - SM6_B(m)
  - TPSA
  - fukui_minus_max
  - TI2_L
  - SdssC
  provenance:
    tuned: '2026-08-25'
    cv_f1: 0.778
    test_f1: 0.81
